### ISSUE TITLE
Integrate Razor templating engine

### ISSUE THREAD

**Issue by wreyniers** [bythepixel/kyrio-go2broadband#18]
https://razorengine.codeplex.com/

**Comment by NathanBurkett** [comment]
If/when this is pushed into active development, the idea here is that we want to keep our templating DRY without steamrolling any .NET modifications that were previously made.

The templates need to be compile-able locally so a developer could work on the project without having it inside of a .NET ecosystem.

https://github.com/magicdawn/gulp-razor-tmpl is an NPM package that compiles Razor templates to static html. Presumably, the Razor templates could stay (relatively) the same for input into the separate .NET application and still be used to actively build/test a static html site.
