### ISSUE TITLE
Improve field input labels/placeholder behavior

### ISSUE THREAD

**Issue by wreyniers** [bythepixel/kyrio-go2broadband#8]
Getting label inputted data overlap when a user navigates away from this page and comes back. This behavior also happens in IE when you refresh the page after entering data:

![image](https://cloud.githubusercontent.com/assets/2293035/19325750/ccd40ebc-9084-11e6-8a3b-0cf221238d26.png)

**Comment by NathanBurkett** [comment]
@NathanBurkett fire this event on page load to check for inputs already populated: https://github.com/bythepixel/kyrio-go2broadband/blob/master/assets/js/components/form.js#L28
